### ISSUE TITLE
Graphs not showing

### ISSUE THREAD

**Issue by JP-sDEV** [ryantcullen/stock-bot#9]
the graphs are not showing for wsl2 running a virtual environment, is that normal?

**Comment by JP-sDEV** [comment]
i can get it to work if i save it locally and open it

**Comment by GoodNotGreat** [comment]
I am having the same issue. Does it have to do with the f-strings?

**Comment by ryantcullen** [comment]
Hey guys, I'll change the f-strings to string.format() syntax. Go ahead and make the change now if you want otherwise I'll get on it in a couple hours.

**Comment by GoodNotGreat** [comment]
That's what I figured. But the F-strings should work with the latest version of python. If you could repost, that would be great. Thanks. I cant wait to input GME.

**Comment by GoodNotGreat** [comment]
I'm still having trouble. Can you post your edit?

**Comment by ryantcullen** [comment]
I made the change. Enjoy!
